### ISSUE TITLE
[Status system] Call to undefined function pass_cookie()

### ISSUE THREAD

**Issue by mchiappinam** [dylanhansch/SystemStatus#13]
Fatal error: Call to undefined function pass_cookie() in /home/mchiappinam/public_html/status/login.php on line 35

**Comment by dylanhansch** [comment]
When exactly do you get this message? After installation, during, or before? Additionally, mind providing your PHP version and web server version?

**Comment by mchiappinam** [comment]
On login... 
@edit 

Solved, sorry and thanks... (tidies alone)

**Comment by dylanhansch** [comment]
Alright. It wasn't an issue with the code was it?
