### ISSUE TITLE
Issues when running install.php for the first time

### ISSUE THREAD

**Issue by stxyzth** [dylanhansch/SystemStatus#2]
Getting three errors when I first run the install.php file after I uploaded all the files.

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/node/public_html/newstatus/install.php:94) in /home/node/public_html/newstatus/global.php on line 3

Table 'node_stat.users' doesn't exist

Fatal error: Call to a member function bind_param() on a non-object in /home/node/public_html/newstatus/global.php on line 62

I've setup the basedirectory in config.php as well as correct MySQL DB details.

**Comment by dylanhansch** [comment]
Ah yes, I believe this is an error with how I wrote the install script. I think I ended up patching this in production, however never pushed to the git repo.

I'll get that updated ASAP and reference this issue in the commit so you get notified of the fix.

**Comment by dylanhansch** [comment]
@stxyzth do you get this error upon executing the install script or after you get the "success" message and try to load the main page?

Could you also attach a pastebin of any web server (apache?) error logs?

**Comment by stxyzth** [comment]
Neither, it's when I login to the admin area. The client login is actually fine, it's just the admin section that doesn't load properly.

There is nothing in Apache's error logs (unfortunately).

**Comment by dylanhansch** [comment]
Could you take a look at your MySQL database in the users table and tell me if the default user has been created successfully?

**Comment by stxyzth** [comment]
Apologies for my last comment, it was actually with regards to another issue on github I got confused with this one! (Main comment still relevant though)

With regards to the DB, there is actually no tables in it.

EDIT: To also answer your question before, the error occurred after the success message.

**Comment by dylanhansch** [comment]
Okay, I'll have to rewrite the install script.

**Comment by dylanhansch** [comment]
Oops, did not mean to close the issue. I've committed a "hot fix" for the issue. Just replace your install.php with the new one and let me know if you are having any issues.

**Comment by stxyzth** [comment]
Worked like a charm, thanks!

**Comment by dylanhansch** [comment]
Great to hear! You're welcome.
